apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
    protocol: TCP
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: europe-west2-docker.pkg.dev/gq-cloud-computing/tripmeal-ilakehal-repo/tripmeal-web:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_NAME
          value: "tripmealdb"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_HOST
          value: "db-service"
        - name: DATABASE_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: TRIPMEAL_KEY
          value: "my-secret-key"
        - name: SERVER_PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: europe-west2-docker.pkg.dev/gq-cloud-computing/tripmeal-ilakehal-repo/tripmeal-db:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "tripmealdb"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
  volumeClaimTemplates:
  - metadata:
      name: tripmeal-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
